name: Emscripten

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Setup Emscripten SDK
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 5.0.1

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake (Emscripten)
        run: |
          emcmake cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build with CMake (Emscripten)
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Prepare Pages artifact
        run: |
          mkdir pages
          cp export/index.html pages/
          cp export/ogp-1200x1200.png pages/
          cp export/open8.data pages/
          cp export/open8.js pages/
          cp export/open8.wasm pages/
          cp export/style.css pages/
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: pages

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
