name: Emscripten

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Setup Emscripten SDK
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 5.0.1

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake (Emscripten)
        run: |
          emcmake cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build with CMake (Emscripten)
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Push build to ngagesdk.github.io
        env:
          OPEN8_TOKEN: ${{ secrets.OPEN8_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone https://x-access-token:${OPEN8_TOKEN}@github.com/ngagesdk/ngagesdk.github.io.git deploy-repo

          rm -rf deploy-repo/open8/*

          cp export/index.html export/ogp-1200x1200.png export/open8.data export/open8.js export/open8.wasm export/style.css deploy-repo/open8/

          cd deploy-repo

          git add ./open8/*
          git commit -m "Update build from CI" || echo "No changes to commit"
          git push origin main

      - name: Archive open8
        uses: actions/upload-artifact@v4
        with:
          name: open8-Emscripten
          path: |
            export/index.html
            export/ogp-1200x1200.png
            export/open8.data
            export/open8.js
            export/open8.wasm
            export/style.css
