name: Haiku OS

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/haiku/cross-compiler:x86_64-r1beta5

    steps:
      - uses: actions/checkout@v4

      - name: Configure project
        run: |
          cmake -S . \
                -B build \
                -G Ninja \
                -DCMAKE_C_COMPILER=x86_64-unknown-haiku-gcc \
                -DCMAKE_CXX_COMPILER=x86_64-unknown-haiku-g++ \
                -DCMAKE_SYSTEM_NAME=Haiku \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build project
        run: cmake --build build --config ${{ env.BUILD_TYPE }}
