name: RISC OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: riscosdotinfo/riscos-gccsdk-4.7:latest

    steps:
      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y cmake ninja-build

      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=/home/riscos/env/toolchain-riscos.cmake \
            -DRISCOS=ON \
            -DSDL_GCC_ATOMICS=OFF \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --parallel
